# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: evearakaki/hawk-kotlin
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

virtualService:
  enabled: false
  host: hawk-kotlin.arakaki.in

envirolmentVariales:
    mongodb_uri: ---
    twitter_crd: ---
    hashtags: apifirst,devops,cloudfirst,microservices,apigateway,oauth,swagger,raml,openapis

imagePullSecrets: []

nameOverride: ""

fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
